export const mockTasks = [
  {
    id: '1',
    date: '2025-05-26',
    category: 'Personal',
    content: 'Review daily goals before sleeping',
    isCompleted: true,
  },
  {
    id: '2',
    date: '2025-05-26',
    category: 'Personal',
    content: 'Write weekly status update',
    isCompleted: false,
  },
  {
    id: '3',
    date: '2025-05-26',
    category: 'Personal',
    content: 'Call dentist to reschedule appointment',
    isCompleted: false,
  },
  {
    id: '4',
    date: '2025-05-26',
    category: 'Design',
    content: 'Review design feedback from client',
    isCompleted: false,
  },
  {
    id: '5',
    date: '2025-05-26',
    category: 'Design',
    content: 'Sketch wireframes for new feature',
    isCompleted: true,
  },
  {
    id: '6',
    date: '2025-05-26',
    category: 'House',
    content: 'Vacuum living room',
    isCompleted: false,
  },

  // --- 2025-05-27 ---
  {
    id: '7',
    date: '2025-05-27',
    category: 'Personal',
    content: 'Go for a 30-minute walk',
    isCompleted: false,
  },
  {
    id: '8',
    date: '2025-05-27',
    category: 'Personal',
    content: 'Stretch for 15 minutes',
    isCompleted: true,
  },
  {
    id: '9',
    date: '2025-05-27',
    category: 'Design',
    content: 'Create icons for dashboard',
    isCompleted: false,
  },
  {
    id: '10',
    date: '2025-05-27',
    category: 'Design',
    content: 'Design new landing page section',
    isCompleted: false,
  },
  {
    id: '11',
    date: '2025-05-27',
    category: 'House',
    content: 'Water indoor plants',
    isCompleted: false,
  },

  // --- 2025-05-28 ---
  {
    id: '12',
    date: '2025-05-28',
    category: 'Personal',
    content: 'Read a chapter from a book',
    isCompleted: false,
  },
  {
    id: '13',
    date: '2025-05-28',
    category: 'Design',
    content: 'Update color palette in design system',
    isCompleted: true,
  },
  {
    id: '14',
    date: '2025-05-28',
    category: 'Design',
    content: 'Prepare a design presentation',
    isCompleted: false,
  },
  {
    id: '15',
    date: '2025-05-28',
    category: 'House',
    content: 'Clean kitchen shelves',
    isCompleted: false,
  },
  {
    id: '16',
    date: '2025-05-28',
    category: 'House',
    content: 'Take out the trash',
    isCompleted: true,
  },

  // --- 2025-05-29 ---
  {
    id: '17',
    date: '2025-05-29',
    category: 'Personal',
    content: 'Journal for 10 minutes',
    isCompleted: false,
  },
  {
    id: '18',
    date: '2025-05-29',
    category: 'Design',
    content: 'Sync with frontend team on UI changes',
    isCompleted: false,
  },
  {
    id: '19',
    date: '2025-05-29',
    category: 'Design',
    content: 'Review pull request with design tweaks',
    isCompleted: true,
  },
  {
    id: '20',
    date: '2025-05-29',
    category: 'House',
    content: 'Do the laundry',
    isCompleted: false,
  },

  // --- 2025-05-30 ---
  {
    id: '21',
    date: '2025-05-30',
    category: 'Personal',
    content: 'Meal prep for the weekend',
    isCompleted: false,
  },
  {
    id: '22',
    date: '2025-05-30',
    category: 'Personal',
    content: 'Grocery shopping',
    isCompleted: true,
  },
  {
    id: '23',
    date: '2025-05-30',
    category: 'Design',
    content: 'Brainstorm homepage redesign',
    isCompleted: false,
  },
  {
    id: '24',
    date: '2025-05-30',
    category: 'Design',
    content: 'Export assets for mobile team',
    isCompleted: false,
  },
  {
    id: '25',
    date: '2025-05-30',
    category: 'House',
    content: 'Organize bookshelf',
    isCompleted: true,
  },

  // --- 2025-05-31 ---
  {
    id: '26',
    date: '2025-05-31',
    category: 'Personal',
    content: 'Practice mindfulness meditation',
    isCompleted: false,
  },
  {
    id: '27',
    date: '2025-05-31',
    category: 'Design',
    content: 'Finish portfolio case study',
    isCompleted: false,
  },
  {
    id: '28',
    date: '2025-05-31',
    category: 'Design',
    content: 'Create mood board for client pitch',
    isCompleted: true,
  },
  {
    id: '29',
    date: '2025-05-31',
    category: 'House',
    content: 'Clean windows',
    isCompleted: false,
  },
  {
    id: '30',
    date: '2025-05-31',
    category: 'House',
    content: 'Reorganize pantry',
    isCompleted: false,
  },

  // --- 2025-06-01 ---
  {
    id: '31',
    date: '2025-06-01',
    category: 'Personal',
    content: 'Stretch after waking up',
    isCompleted: true,
  },
  {
    id: '32',
    date: '2025-06-01',
    category: 'Personal',
    content: 'Backup phone data',
    isCompleted: false,
  },
  {
    id: '33',
    date: '2025-06-01',
    category: 'Design',
    content: 'Prepare Figma prototype',
    isCompleted: false,
  },
  {
    id: '34',
    date: '2025-06-01',
    category: 'Design',
    content: 'Test new button styles',
    isCompleted: false,
  },
  {
    id: '35',
    date: '2025-06-01',
    category: 'House',
    content: 'Fix leaky faucet',
    isCompleted: true,
  },
  {
    id: '36',
    date: '2025-06-01',
    category: 'House',
    content: 'Sweep the garage',
    isCompleted: false,
  },
];
